### ISSUE TITLE
creatHistoryControllerTest

### ISSUE THREAD

**Issue by sherxonov** [dr-dilshod/SDLCExample#9]
domla.
1.bazaga ma'lumot qo'shib bo'lmin duribdi.
2.bazadan ma'lumot o'qib bo'min duribdi 

bazadan o'chirish va yangilash to'g'ri ishlab duribdi.
1af949f

**Comment by dr-dilshod** [comment]
Baza bilan ulanishlarni tekshirish uchun, bazadagi tablitsang kerak bo'ladi. PHPMyAdmin ga kirib SQL faylni ham githubga yuklashingiz kerak. Masalan, man o'zimnikini uz.ubtuit.se.medhistoryservice.config ni ichinda *.sql formatda yuklab qo'yibman.

**Comment by dr-dilshod** [comment]
This is fixed in commit  71e01f8
